### ISSUE TITLE
Question about Starlette

### ISSUE THREAD

**Issue by dineshbvadhia** [matyasrichter/fastapi-injector#32]
Could fastapi-injector be made to work with a Starlette only app?

**Comment by matyasrichter** [comment]
Hi @dineshbvadhia, sorry for the late response. `fastapi-injector` uses FastAPI's [`Depends`](https://fastapi.tiangolo.com/reference/dependencies/#depends) and hooks into the FastAPI app instance, so it's not possible to use it with Starlette at the moment, sorry.
