### ISSUE TITLE
Security dependency injection

### ISSUE THREAD

**Issue by nistvan86** [matyasrichter/fastapi-injector#9]
I'm trying to use your library together with [fastapi-jwt](https://github.com/k4black/fastapi-jwt).
I'm defining a token access object inside a module:

    class SecurityModule(Module):
        @provider
        @singleton
        def provide_access_security(self, config: AppConfig = Injected(AppConfig)) -> JwtAccessBearerCookie:
            return JwtAccessBearerCookie(
                secret_key=config.server.jwt_secret,
                auto_error=False,
                # change access token validation timedelta
                access_expires_delta=timedelta(
                    hours=config.server.access_token_expiry_hours),
            )

As per the [usage example of fastapi-jwt](https://github.com/k4black/fastapi-jwt#usage), the validated credentials can be injected into the FastAPI handler method using `Security` which is a variant of `Depends`.

I've copied your `Injected` helper and created an `InjectedSecurity` equivalent which returns `Security` instead of `Depends`.
    
    def InjectedSecurity(interface: BoundInterface) -> Any:  # type: ignore
        """
        Based on Injected, but allows using the dependency injection inside a Security param wrapper
        """
    
        async def inject_into_route(request: Request) -> BoundInterface:
            return get_injector_instance(request.app).get(interface) # type: ignore
    
        return Security(inject_into_route)

Then I'm using this in a route like this:
  
    @router.get("/")
    async def read_items(credentials: JwtAuthorizationCredentials = InjectedSecurity(JwtAccessBearerCookie)) -> str:
        return "Hello World"

The problem is that I'm only getting the `JwtAccessBearerCookie` object as the `credentials` param, not the evaluated `JwtAuthorizationCredentials`. FastAPI doesn't call the `__call__` method on `JwtAccessBearerCookie`.
This seems to be called ["callable" instance](https://fastapi.tiangolo.com/advanced/advanced-dependencies/#a-callable-instance) by the documentation of FastAPI.

Can this be solved somehow?

**Comment by nistvan86** [comment]
Sorry, wrong button. :disappointed_relieved:

**Comment by matyasrichter** [comment]
Hi, @nistvan86!

I'm afraid this is not a use case that can be solved using an IoC container like `injector`. The classes provided by `fastapi-jwt` are FastAPI dependencies that receive input from the request object. Their `__call__` method [here](https://github.com/k4black/fastapi-jwt/blob/8d1afa7f3ad4fec4f3db32890910c65ebc08c96a/fastapi_jwt/jwt.py#L347) uses its own `Security` dependencies to get the access token from the request's headers.

`Injected`, on the other hand, can be used to get instances of classes you can call in your request handler. It's essentially a factory for quickly creating functions that call `injector.get` for you. For example, you could use `Injected` to get an instance of a class that, given the contents of the `sub` claim from your JWT, fetches a User instance from the database, like so:
```python
access_security: JwtAccessBearerCookie  = JwtAccessBearerCookie(
    secret_key="secret",
    access_expires_delta=timedelta(hours=1),
)

@router.get("/")
async def read_items(
    credentials: JwtAuthorizationCredentials = Security(access_security),
    user_service: UserService = Injected(UserService)
) -> Any:
    user = await user_service.get_user(credentials.subject)
    ...
```

I understand that you're trying to use `injector` to get the secret for your JWTs without instantiating `AppConfig` on the module level. It's a common pattern in Python libraries to require "global" initialization like that, and it's not a pattern I'm very fond of. I suggest switching to a jwt library that doesn't require this, like [pyjwt](https://github.com/jpadilla/pyjwt/) or [python-jose](https://github.com/mpdavis/python-jose). Then you could do something like this:
```python
security = HTTPBearer()

async def get_current_user_id(
  credentials: HTTPAuthorizationCredentials = Security(security),
  config: AppConfig = Injected(AppConfig)
) -> str:
    # here, you can use a JWT library of your choice to decode the token
    claims = jwt.decode(credentials.credentials, config.secret, ...)
    return claims["sub"]

@router.get("/")
async def read_items(user_id: str = Depends(get_current_user_id):
    ....
```

Hope that helps.

**Comment by nistvan86** [comment]
Hi @matyasrichter !
Thank you for the detailed answer and suggestion. 

I was trying to avoid implementing the boilerplate part of JWT auth myself, that's why I had high hopes for fastapi-jwt, but your suggestion seems not so much more complicated, so I'll try and rewrite my code into this format.
